package graphql

import (
	"reflect"
	"strconv"

	"github.com/vektah/gqlparser/v2/ast"
	"github.com/vektah/gqlparser/v2/parser"
)

// This file contains code to parse GraphQL queries. It uses the GraphQL parser
// from gqlparser, and stores its output value in a more convenient format.

// valueToJSON takes a gqlparser ast value and converts it to a value like those
// generated by json.Unmarshal.
func valueToJSON(value *ast.Value, vars map[string]interface{}) (interface{}, error) {
	if value == nil {
		return nil, nil
	}

	switch value.Kind {
	case ast.IntValue:
		v, err := strconv.ParseInt(value.Raw, 10, 64)
		if err != nil {
			return nil, NewClientError("bad int arg: %s", err)
		}
		// Integers are represented as float64 so that an argument from a literal
		// and the same argument from a JSON variable have the same Go type —
		// except where that would lose precision. Above 2^53 a float64 cannot
		// hold every integer, and rounding an Int64 literal to the nearest
		// representable double would corrupt it silently, so such a value keeps
		// its int64 type and the scalar argument parsers accept both.
		if asFloat := float64(v); int64(asFloat) == v {
			return asFloat, nil
		}
		return v, nil

	case ast.FloatValue:
		v, err := strconv.ParseFloat(value.Raw, 64)
		if err != nil {
			return nil, NewClientError("bad float arg: %s", err)
		}
		return v, nil

	case ast.StringValue, ast.BlockValue:
		return value.Raw, nil

	case ast.BooleanValue:
		v, err := strconv.ParseBool(value.Raw)
		if err != nil {
			return nil, NewClientError("bad boolean arg: %s", err)
		}
		return v, nil

	case ast.EnumValue:
		return value.Raw, nil

	case ast.NullValue:
		return nil, nil

	case ast.Variable:
		actual, ok := vars[value.Raw]
		if !ok {
			return nil, nil
		}
		return actual, nil

	case ast.ObjectValue:
		obj := make(map[string]interface{})
		for _, field := range value.Children {
			if _, found := obj[field.Name]; found {
				return nil, NewClientError("duplicate field")
			}
			v, err := valueToJSON(field.Value, vars)
			if err != nil {
				return nil, err
			}
			obj[field.Name] = v
		}
		return obj, nil

	case ast.ListValue:
		list := make([]interface{}, 0, len(value.Children))
		for _, item := range value.Children {
			v, err := valueToJSON(item.Value, vars)
			if err != nil {
				return nil, err
			}
			list = append(list, v)
		}
		return list, nil

	default:
		return nil, NewClientError("unsupported value type: %v", value.Kind)
	}
}

func parseDirectives(directives ast.DirectiveList, vars map[string]interface{}) ([]*Directive, error) {
	d := make([]*Directive, 0, len(directives))
	for _, directive := range directives {
		args, err := argsToJSON(directive.Arguments, vars)
		if err != nil {
			return nil, err
		}

		d = append(d, &Directive{
			Name: directive.Name,
			Args: args,
		})
	}
	return d, nil
}

// argsToJSON converts a gqlparser ast argument list to a json.Marshal-style
// map[string]interface{}.
func argsToJSON(input ast.ArgumentList, vars map[string]interface{}) (map[string]interface{}, error) {
	args := make(map[string]interface{})
	for _, arg := range input {
		if _, found := args[arg.Name]; found {
			return nil, NewClientError("duplicate arg")
		}
		value, err := valueToJSON(arg.Value, vars)
		if err != nil {
			return nil, err
		}
		args[arg.Name] = value
	}
	return args, nil
}

// parseSelectionSet takes a gqlparser selection set and converts it to a
// simplified *SelectionSet, binding vars.
func parseSelectionSet(input ast.SelectionSet, globalFragments map[string]*Fragment, vars map[string]interface{}) (*SelectionSet, error) {
	if input == nil {
		return nil, nil
	}

	var selections []*Selection
	var fragments []*Fragment
	for _, selection := range input {
		switch selection := selection.(type) {
		case *ast.Field:
			alias := selection.Alias
			if alias == "" {
				alias = selection.Name
			}

			directives, err := parseDirectives(selection.Directives, vars)
			if err != nil {
				return nil, err
			}

			args, err := argsToJSON(selection.Arguments, vars)
			if err != nil {
				return nil, err
			}

			selectionSet, err := parseSelectionSet(selection.SelectionSet, globalFragments, vars)
			if err != nil {
				return nil, err
			}

			newSelection := &Selection{
				Alias:        alias,
				Name:         selection.Name,
				UnparsedArgs: args,
				SelectionSet: selectionSet,
			}

			if len(selection.Directives) > 0 {
				newSelection.Directives = directives
			}
			selections = append(selections, newSelection)

		case *ast.FragmentSpread:
			directives, err := parseDirectives(selection.Directives, vars)
			if err != nil {
				return nil, err
			}

			fragment, found := globalFragments[selection.Name]
			if !found {
				return nil, NewClientError("unknown fragment")
			}

			// Every spread gets its own *Fragment so that directives on one
			// spread of a fragment do not leak into its other spreads. The
			// SelectionSet is shared, which is what fragment reuse means.
			spread := &Fragment{
				On:           fragment.On,
				SelectionSet: fragment.SelectionSet,
			}
			if len(directives) > 0 {
				spread.Directives = directives
			}

			fragments = append(fragments, spread)

		case *ast.InlineFragment:
			directives, err := parseDirectives(selection.Directives, vars)
			if err != nil {
				return nil, err
			}

			selectionSet, err := parseSelectionSet(selection.SelectionSet, globalFragments, vars)
			if err != nil {
				return nil, err
			}

			// An inline fragment without a type condition applies to the
			// enclosing type; it is represented by an empty On.
			newFragment := &Fragment{
				On:           selection.TypeCondition,
				SelectionSet: selectionSet,
			}

			if len(directives) > 0 {
				newFragment.Directives = directives
			}

			fragments = append(fragments, newFragment)
		}
	}

	selectionSet := &SelectionSet{
		Selections: selections,
		Fragments:  fragments,
	}
	return selectionSet, nil
}

type visitState int

const (
	none visitState = iota
	visiting
	visited
)

// orderFragments finds fragments that transitively include themselves, as well
// as fragments the document defines but no operation spreads, and returns the
// names of the fragments the selected operation needs in dependency order: a
// fragment always appears after every fragment it spreads.
//
// It runs over the gqlparser AST, before conversion, because fragment identity
// there is a name rather than a pointer. The ordering matters because
// converting a fragment spread copies the spread fragment's already-converted
// selection set.
//
// The unused check looks at *every* operation in the document, not only the one
// being run: a document holding two operations with a fragment each is legal,
// and the fragment belonging to the operation not being run is not unused.
func orderFragments(document *ast.QueryDocument, operation *ast.OperationDefinition, fragments map[string]*ast.FragmentDefinition) ([]string, error) {
	state := make(map[string]visitState, len(fragments))
	order := make([]string, 0, len(fragments))

	var visitFragment func(string) error
	var visitSelectionSet func(ast.SelectionSet) error

	visitSelectionSet = func(selectionSet ast.SelectionSet) error {
		for _, selection := range selectionSet {
			switch selection := selection.(type) {
			case *ast.Field:
				if err := visitSelectionSet(selection.SelectionSet); err != nil {
					return err
				}
			case *ast.InlineFragment:
				if err := visitSelectionSet(selection.SelectionSet); err != nil {
					return err
				}
			case *ast.FragmentSpread:
				if err := visitFragment(selection.Name); err != nil {
					return err
				}
			}
		}
		return nil
	}

	visitFragment = func(name string) error {
		switch state[name] {
		case visiting:
			return NewClientError("fragment contains itself")
		case visited:
			return nil
		}

		fragment, found := fragments[name]
		if !found {
			return NewClientError("unknown fragment")
		}

		state[name] = visiting
		if err := visitSelectionSet(fragment.SelectionSet); err != nil {
			return err
		}
		state[name] = visited
		order = append(order, name)

		return nil
	}

	if err := visitSelectionSet(operation.SelectionSet); err != nil {
		return nil, err
	}

	// The fragments the selected operation needs, in the order they must be
	// converted. Anything reached below this point belongs to another operation
	// and is never converted.
	order = order[:len(order):len(order)]

	for _, other := range document.Operations {
		if other == operation {
			continue
		}
		if err := visitSelectionSet(other.SelectionSet); err != nil {
			return nil, err
		}
	}

	for name := range fragments {
		if state[name] != visited {
			return nil, NewClientError("unused fragment")
		}
	}
	return order, nil
}

// detectConflicts finds conflicts
//
// Conflicts are selections that can not be merged, for example
//
//	foo: bar(id: 123)
//	foo: baz(id: 456)
//
// A query cannot contain both selections, because they have the same alias
// with different source names, and they also have different arguments.
func detectConflicts(selectionSet *SelectionSet) error {
	state := make(map[*SelectionSet]visitState)

	var visitChild func(*SelectionSet) error
	visitChild = func(selectionSet *SelectionSet) error {
		if state[selectionSet] == visited {
			return nil
		}
		state[selectionSet] = visited

		selections := make(map[string]*Selection)

		var visitSibling func(*SelectionSet) error
		visitSibling = func(selectionSet *SelectionSet) error {
			for _, selection := range selectionSet.Selections {
				if other, found := selections[selection.Alias]; found {
					if other.Name != selection.Name {
						return NewClientError("same alias with different name")
					}
					if !reflect.DeepEqual(other.UnparsedArgs, selection.UnparsedArgs) {
						return NewClientError("same alias with different args")
					}
				} else {
					selections[selection.Alias] = selection
				}
			}

			for _, fragment := range selectionSet.Fragments {
				if err := visitSibling(fragment.SelectionSet); err != nil {
					return err
				}
			}

			return nil
		}

		return visitSibling(selectionSet)
	}

	return visitChild(selectionSet)
}

type Query struct {
	Name string
	Kind string
	*SelectionSet
}

// Parse parses an input GraphQL string into a *Query.
//
// Parse validates that the query looks syntactically correct and contains no
// cycles or unused fragments or immediate conflicts. However, it does not
// validate that the query is legal under a given schema, which instead is done
// by (*Validator).ValidateDocument and PrepareQuery.
//
// If the document contains more than one operation, use ParseOperation to say
// which one to run.
func Parse(source string, vars map[string]interface{}) (*Query, error) {
	return ParseOperation(source, vars, "")
}

// ParseOperation parses an input GraphQL string into a *Query, selecting the
// operation named operationName. An empty operationName selects the document's
// only operation, and is an error if the document holds more than one.
func ParseOperation(source string, vars map[string]interface{}, operationName string) (*Query, error) {
	document, err := parser.ParseQuery(&ast.Source{Input: source})
	if err != nil {
		return nil, NewClientError("%s", err.Error())
	}
	return parseDocument(document, vars, operationName)
}

// selectOperation picks the operation to execute out of a parsed document.
func selectOperation(document *ast.QueryDocument, operationName string) (*ast.OperationDefinition, error) {
	if len(document.Operations) == 0 {
		return nil, NewClientError("must have a single query")
	}

	if operationName == "" {
		if len(document.Operations) > 1 {
			return nil, NewClientError("must provide operation name if query contains multiple operations")
		}
		return document.Operations[0], nil
	}

	for _, operation := range document.Operations {
		if operation.Name == operationName {
			return operation, nil
		}
	}
	return nil, NewClientError("unknown operation name: %s", operationName)
}

// parseDocument converts an already-parsed gqlparser document into a *Query.
func parseDocument(document *ast.QueryDocument, vars map[string]interface{}, operationName string) (*Query, error) {
	operation, err := selectOperation(document, operationName)
	if err != nil {
		return nil, err
	}

	fragmentDefinitions := make(map[string]*ast.FragmentDefinition, len(document.Fragments))
	for _, fragment := range document.Fragments {
		if _, found := fragmentDefinitions[fragment.Name]; found {
			return nil, NewClientError("duplicate fragment")
		}
		fragmentDefinitions[fragment.Name] = fragment
	}

	rv := &Query{
		Name:         operation.Name,
		Kind:         string(operation.Operation),
		SelectionSet: nil,
	}

	vars, err = applyVariableDefaults(operation, vars)
	if err != nil {
		return rv, err
	}

	order, err := orderFragments(document, operation, fragmentDefinitions)
	if err != nil {
		return rv, err
	}

	globalFragments := make(map[string]*Fragment, len(fragmentDefinitions))
	for name, fragment := range fragmentDefinitions {
		globalFragments[name] = &Fragment{
			On: fragment.TypeCondition,
		}
	}

	// Dependency order, so that a spread always copies a converted selection set.
	for _, name := range order {
		selectionSet, err := parseSelectionSet(fragmentDefinitions[name].SelectionSet, globalFragments, vars)
		if err != nil {
			return rv, err
		}
		globalFragments[name].SelectionSet = selectionSet
	}

	selectionSet, err := parseSelectionSet(operation.SelectionSet, globalFragments, vars)
	if err != nil {
		return rv, err
	}

	if err := detectConflicts(selectionSet); err != nil {
		return rv, err
	}

	rv.SelectionSet = selectionSet

	return rv, nil
}

// applyVariableDefaults returns vars with the operation's declared default
// values filled in for any variable the caller did not supply.
//
// Following the specification's CoerceVariableValues, a variable that was
// supplied explicitly as null keeps its null: only an absent variable takes the
// default.
func applyVariableDefaults(operation *ast.OperationDefinition, vars map[string]interface{}) (map[string]interface{}, error) {
	var defaulted map[string]interface{}

	for _, variableDefinition := range operation.VariableDefinitions {
		if variableDefinition.DefaultValue == nil {
			continue
		}
		if _, provided := vars[variableDefinition.Variable]; provided {
			continue
		}

		if defaulted == nil {
			defaulted = make(map[string]interface{}, len(vars)+1)
			for k, v := range vars {
				defaulted[k] = v
			}
		}

		// Default values may not reference variables, so an empty variable map
		// is the correct environment to evaluate them in.
		value, err := valueToJSON(variableDefinition.DefaultValue, nil)
		if err != nil {
			// A literal that parses but cannot be converted — an integer beyond
			// int64, say — is a real error and reported as one rather than
			// leaving the variable quietly unset.
			return nil, NewClientError("bad default value for $%s: %s", variableDefinition.Variable, err)
		}
		defaulted[variableDefinition.Variable] = value
	}

	if defaulted != nil {
		return defaulted, nil
	}
	return vars, nil
}

// FlattenAll flattens a selection set keeping every fragment, regardless of
// type condition. It is the right call when the caller has already narrowed the
// fragments itself.
func FlattenAll(selectionSet *SelectionSet) ([]*Selection, error) {
	return Flatten(selectionSet, nil)
}

func MustParse(source string, vars map[string]interface{}) *Query {
	query, err := Parse(source, vars)
	if err != nil {
		panic(err)
	}
	return query
}

// Flatten takes a SelectionSet and flattens it into an array of selections
// with unique aliases, keeping only the fragments that apply to typ.
//
// Passing a nil typ keeps every fragment, which is what callers that have
// already filtered by type condition want.
//
// A GraphQL query (the SelectionSet) is allowed to contain the same key
// multiple times, as well as fragments. For example,
//
//	{
//	  groups { name }
//	  groups { name id }
//	  ... on Organization { groups { widgets { name } } }
//	}
//
// Flatten simplifies the query into an array of selections, merging fields,
// resulting in something like the new query
//
//	groups: { name name id { widgets { name } } }
//
// Flatten does _not_ flatten out the inner queries, so the name above does not
// get flattened out yet.
func Flatten(selectionSet *SelectionSet, typ *Object) ([]*Selection, error) {
	grouped := make(map[string][]*Selection)

	state := make(map[*SelectionSet]visitState)
	var visit func(*SelectionSet) error
	visit = func(selectionSet *SelectionSet) error {
		if state[selectionSet] == visited {
			return nil
		}

		for _, selection := range selectionSet.Selections {
			// @skip and @include are applied per occurrence, before fields are
			// merged. A skipped occurrence contributes nothing — not even its
			// sub-selections, which would otherwise be merged into a sibling
			// occurrence of the same field and resolved anyway.
			ok, err := ShouldIncludeNode(selection.Directives)
			if err != nil {
				return err
			}
			if !ok {
				continue
			}
			grouped[selection.Alias] = append(grouped[selection.Alias], selection)
		}

		for _, fragment := range selectionSet.Fragments {
			if !FragmentApplies(fragment.On, typ) {
				continue
			}
			ok, err := ShouldIncludeNode(fragment.Directives)
			if err != nil {
				return err
			}
			if ok {
				if err := visit(fragment.SelectionSet); err != nil {
					return err
				}
			}
		}

		state[selectionSet] = visited
		return nil
	}

	if err := visit(selectionSet); err != nil {
		return nil, err
	}

	var flattened []*Selection
	for _, selections := range grouped {
		if len(selections) == 1 || selections[0].SelectionSet == nil {
			flattened = append(flattened, selections[0])
			continue
		}

		merged := &SelectionSet{}
		for _, selection := range selections {
			// A group can hold a selection without a sub-selection alongside one
			// with: the conflict check compares names and arguments, not
			// shapes, and schema validation — which would reject the pair —
			// does not have to have been run.
			if selection.SelectionSet == nil {
				continue
			}
			merged.Selections = append(merged.Selections, selection.SelectionSet.Selections...)
			merged.Fragments = append(merged.Fragments, selection.SelectionSet.Fragments...)
		}

		merge := &Selection{
			Name:         selections[0].Name,
			Alias:        selections[0].Alias,
			ParentType:   selections[0].ParentType,
			UnparsedArgs: selections[0].UnparsedArgs,
			Args:         selections[0].Args,
			SelectionSet: merged,
		}
		// Per-type arguments travel with the merged selection; without them an
		// interface field selected twice would fall back to Args.
		for typeName, args := range selections[0].argsByParentType {
			merge.SetArgsForType(typeName, args)
		}
		flattened = append(flattened, merge)
	}

	return flattened, nil
}
